interpolate values into include files
paketo-buildpacks/nginx pull request #212
Opened 2021-03-30 21:10 UTC by fg-j

Resolves #165

## Summary

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

2021-03-30 21:11 UTC, fg-j commented
Still to do: support file masks like `include /home/*.conf`

2021-04-01 14:12 UTC, arjun024 requested changes
Except a tiny requested change, looks pretty good to me

2021-04-01 14:12 UTC, arjun024 commented on cmd/configure/main.go
> +	includeRe := regexp.MustCompile(`include (\S*.conf);`)
```suggestion
	includeRe := regexp.MustCompile(`include\s+(\S*.conf);`)
```
Nginx is still happy with multiple whitespace between directive and param

2021-04-01 14:28 UTC, arjun024 approved these changes

2021-04-01 14:57 UTC, merged